language: python
python:
  - '3.8'

before_script:
  - pip install pipenv
  - pipenv install --dev

env: DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test && flake8
